name: Release Automation
run-name: Run the script automatically, then pack the result and release.
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  update-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Pack source code
        run: tar -czvf sources.tar.gz README.md LICENSE requirements.txt ./src
      - name: Update lists
        run: python -m src/main.py
      - name: Pack the result
        run: tar -czvf ${{ env.CURRENT_DATE }}.tar.gz adguard_china_list adguard_china_list_with_apple_service forwarding_china_list forwarding_china_list_ipv6 forwarding_china_list_with_apple_service forwarding_china_list_with_apple_service_ipv6
      - name: Publish the release
        uses: ncipollo/release-action@v1.11.2
        env:
          CURRENT_DATE: 
        with:
          title: ${{ env.CURRENT_DATE }}
          artifacts: ${{ env.CURRENT_DATE }}.tar.gz
          tag: ${{ env.CURRENT_DATE }}